#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPTS="$ROOT/.tekton/integration-tests/scripts"
test -x "$SCRIPTS/provision_ec2.sh"
test -x "$SCRIPTS/wait_for_ssh.sh"
test -x "$SCRIPTS/cleanup_ec2.sh"
test -x "$SCRIPTS/extract_version_from_image.sh"
test -x "$SCRIPTS/prepare_workspace.sh"
test -x "$SCRIPTS/run_os_e2e.sh"
test -x "$SCRIPTS/aggregate_results.sh"
test -x "$SCRIPTS/verify_results.sh"
# Syntax check only (no AWS calls)
bash -n "$SCRIPTS/provision_ec2.sh"
bash -n "$SCRIPTS/wait_for_ssh.sh"
bash -n "$SCRIPTS/cleanup_ec2.sh"
bash -n "$SCRIPTS/extract_version_from_image.sh"
bash -n "$SCRIPTS/prepare_workspace.sh"
bash -n "$SCRIPTS/run_os_e2e.sh"
bash -n "$SCRIPTS/aggregate_results.sh"
bash -n "$SCRIPTS/verify_results.sh"
echo "OK"
